apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Adds namespace to all resources.
namespace: k0smotron

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
namePrefix: k0smotron-
nameSuffix: -infrastructure

resources:
- ./crd
- ./rbac
- ../../manager

patches:
- path: manager_config_patch.yaml