# The following manifests contain a self-signed issuer CR and a certificate CR.
# More document can be found at https://docs.cert-manager.io
# WARNING: Targets CertManager v1.0. Check https://cert-manager.io/docs/installation/upgrading/ for breaking changes.
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  labels:
    app.kubernetes.io/name: certificate
    app.kubernetes.io/instance: extension-webhook-cert
    app.kubernetes.io/component: certificate
    app.kubernetes.io/created-by: k0smotron
    app.kubernetes.io/part-of: k0smotron
    app.kubernetes.io/managed-by: kustomize
  name: selfsigned-issuer
  namespace: system
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  labels:
    app.kubernetes.io/name: certificate
    app.kubernetes.io/instance: extension-webhook-cert
    app.kubernetes.io/component: certificate
    app.kubernetes.io/created-by: k0smotron
    app.kubernetes.io/part-of: k0smotron
    app.kubernetes.io/managed-by: kustomize
  name: extension-webhook-cert  # this name should match the one appeared in kustomizeconfig.yaml
  namespace: system
spec:
  # SERVICE_NAME and SERVICE_NAMESPACE will be substituted by kustomize
  dnsNames:
  - SERVICE_NAME.SERVICE_NAMESPACE.svc
  - SERVICE_NAME.SERVICE_NAMESPACE.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: selfsigned-issuer
  secretName: extension-webhook-server-cert
